### PR TITLE
Data component

### LINKED ISSUE #23: Data component
Inspired by URQL and Apollo 2.1, a declarative Data component would greatly simplify the DX.

```jsx
<Data
  action={getPerson}
  variables={{ id: props.personId }}
  options={{ maxAge: 60 }}
>
  {({ data, error, loading }) => (
    <div>
      {lodaing && <div>Lodaing...</div>}
      {error && <div>ERROR: {error.message}</div>}
      {data && <div>Hello {person.name}!</div>}
    </div>
  )}
</Data> 
```

- [React-Apollo 2.1 release notes](https://github.com/apollographql/react-apollo/releases/tag/v2.1.0-beta.0)
- [URQL](https://github.com/FormidableLabs/urql)

### PR DESCRIPTION
**Pull request by cvburgess**
- Add Data component
- Add StoreProvider for a centralized app store
- FIx and upgrade ESLint
- Update docs
- Refactor placeholder from `{ loading: true }` to `null`
- Refactor to use modular lodash
- Refactor cache promise signature

Closes #23

### CODE REVIEW

File: src/withData.jsx [hunk 1]
```diff
@@ -117,48 +95,81 @@ function withData(actions) {
...
       getData = (actionName, options = {}) => {
+        const { store } = this.context;
         const { noCache, ...overrides } = options;
         const appliedParams = this.state.appliedParams[actionName];
         let action;
         let childOptions = {};
 
         if (Array.isArray(actions[actionName])) {
-          action = actions[actionName][0];
+          [action] = actions[actionName];
```
Comment (theY4Kman) [inline src/withData.jsx:105]: Neeeeeaaaaaaat
